#!/usr/bin/env python3
"""
Regenerate the ``paths:`` section of mediamtx.yml from the dashboard DB.

For every company that has a launched pipeline (its index is recorded in
config/companies/_indices.json) we publish one MediaMTX path per enabled,
RTSP-backed camera:

    {admin_username}_cam{i}:
        source: rtsp://127.0.0.1:{8555+index}/cam{i}

That is the annotated DeepStream output for camera ``i`` (ordered by name —
the SAME ordering used by gen_company_config.py and the backend's
cameras.service stream_path). The dashboard builds each camera's browser
HLS/WebRTC URL from this path:

    HLS    : http://<host>:8888/{admin_username}_cam{i}/index.m3u8
    WebRTC : http://<host>:8889/{admin_username}_cam{i}

MediaMTX watches its config file and hot-reloads, so simply rewriting the file
is enough — no restart required.

Everything in mediamtx.yml above the ``paths:`` line is preserved verbatim
(comments and all); only the paths block is regenerated.

Usage:
    python3 tools/gen_mediamtx_paths.py [--yml /home/meta/deploy/mediamtx.yml]
"""
import os
import sys
import json
import argparse

import psycopg2
from dotenv import load_dotenv

load_dotenv("/home/meta/deploy/attendance-system/backend/.env")
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDICES = os.path.join(BASE, "config", "companies", "_indices.json")
DEFAULT_YML = os.environ.get("MEDIAMTX_YML", "/home/meta/deploy/mediamtx.yml")

# Recording settings applied to every generated path (mirrors the original
# hand-written "stream" path so recordings keep working).
RECORD_BLOCK = [
    "    sourceOnDemand: no",
    "    record: yes",
    "    recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S",
    "    recordFormat: fmp4",
    "    recordPartDuration: 1s",
    "    recordDeleteAfter: 48h",
]


def load_indices():
    if os.path.exists(INDICES):
        try:
            return json.load(open(INDICES))
        except Exception:
            pass
    return {}


def build_paths():
    """Return the list of (path_name, source_rtsp) for all companies' cameras."""
    indices = load_indices()
    conn = psycopg2.connect(os.getenv("DATABASE_URL"))
    cur = conn.cursor()
    cur.execute("SELECT company_id, admin_username FROM companies ORDER BY admin_username")
    companies = cur.fetchall()

    paths = []
    for company_id, username in companies:
        # Only publish paths for companies whose pipeline has actually been
        # launched (its index is recorded in _indices.json). This keeps RTSP
        # ports unique per company and avoids dead paths for un-launched tenants.
        if not username or username not in indices:
            continue
        index = int(indices[username])
        rtsp_port = 8555 + index
        cur.execute(
            """SELECT name FROM cameras
               WHERE company_id=%s AND enabled=TRUE
                 AND rtsp_url IS NOT NULL AND rtsp_url<>''
               ORDER BY name""",
            (company_id,),
        )
        cams = cur.fetchall()
        for i, _ in enumerate(cams):
            paths.append((f"{username}_cam{i}", f"rtsp://127.0.0.1:{rtsp_port}/cam{i}"))
    conn.close()
    return paths


def render_block(paths):
    lines = [
        "paths:",
        "  # >>> generated by tools/gen_mediamtx_paths.py from the dashboard DB.",
        "  # >>> Do not hand-edit; re-run the generator (or relaunch a pipeline).",
    ]
    for name, source in paths:
        lines.append(f"  {name}:")
        lines.append(f"    source: {source}")
        lines += RECORD_BLOCK
    if not paths:
        lines.append("  # (no launched pipelines with enabled RTSP cameras yet)")
    # Catch-all so ad-hoc publishers (e.g. a raw camera test) still work.
    lines.append("  all_others:")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yml", default=DEFAULT_YML)
    args = ap.parse_args()

    if not os.path.exists(args.yml):
        sys.exit(f"mediamtx.yml not found: {args.yml}")

    with open(args.yml) as f:
        original = f.read()

    # Preserve everything above the top-level `paths:` line.
    head_lines = []
    for line in original.splitlines():
        if line.rstrip() == "paths:" or line.startswith("paths:"):
            break
        head_lines.append(line)
    head = "\n".join(head_lines).rstrip("\n") + "\n\n"

    paths = build_paths()
    new_content = head + render_block(paths)

    # Atomic write: temp file in the same dir + rename. Only needs directory
    # write permission (so it works even if mediamtx.yml itself is root-owned),
    # and MediaMTX never sees a half-written config during its hot-reload.
    tmp = args.yml + ".tmp"
    with open(tmp, "w") as f:
        f.write(new_content)
    os.replace(tmp, args.yml)

    print(f"Wrote {len(paths)} path(s) to {args.yml}:")
    for name, source in paths:
        print(f"   {name}  <-  {source}")
    if not paths:
        print("   (none — launch a company pipeline with enabled RTSP cameras first)")


if __name__ == "__main__":
    main()
